"""create remaining product domain tables

Revision ID: 4f2a8e7c91bd
Revises: 8ff89ebfafa0
Create Date: 2026-08-26

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "4f2a8e7c91bd"
down_revision: str | Sequence[str] | None = "8ff89ebfafa0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_templates",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "goal_types",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("days_per_week", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "equipment",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "days",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(equipment) = 'array'", name=op.f("ck_training_templates_equipment_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(goal_types) = 'array'",
            name=op.f("ck_training_templates_goal_types_array"),
        ),
        sa.CheckConstraint(
            "days_per_week BETWEEN 1 AND 7", name=op.f("ck_training_templates_days_per_week_range")
        ),
        sa.CheckConstraint(
            "duration_minutes BETWEEN 1 AND 300",
            name=op.f("ck_training_templates_duration_minutes_range"),
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name=op.f("ck_training_templates_name_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_templates")),
        sa.UniqueConstraint("name", name="uq_training_templates_name"),
    )
    op.create_index(
        "ix_training_templates_active_days",
        "training_templates",
        ["is_active", "days_per_week"],
        unique=False,
    )
    op.create_index(
        "ix_training_templates_equipment_gin",
        "training_templates",
        ["equipment"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_training_templates_goal_types_gin",
        "training_templates",
        ["goal_types"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "body_fat_estimates",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("value_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("range_min_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("range_max_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_body_fat_estimates_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_body_fat_estimates")),
    )
    op.create_index(
        "ix_body_fat_estimates_user_calculated",
        "body_fat_estimates",
        ["user_id", "calculated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_body_fat_estimates_user_id"), "body_fat_estimates", ["user_id"], unique=False
    )
    op.create_table(
        "body_measurements",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("waist_cm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("neck_cm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("hip_cm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("conditions", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_body_measurements_version_positive")),
        sa.CheckConstraint(
            "weight_kg IS NOT NULL OR waist_cm IS NOT NULL OR "
            "neck_cm IS NOT NULL OR hip_cm IS NOT NULL",
            name=op.f("ck_body_measurements_at_least_one_measurement"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_body_measurements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_body_measurements")),
    )
    op.create_index(
        op.f("ix_body_measurements_user_id"), "body_measurements", ["user_id"], unique=False
    )
    op.create_index(
        "ix_body_measurements_user_measured",
        "body_measurements",
        ["user_id", "measured_at"],
        unique=False,
    )
    op.create_table(
        "confirmations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("operation_type", sa.String(length=100), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("impact", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'rejected', 'failed', 'expired')",
            name=op.f("ck_confirmations_status"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_confirmations_version_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_confirmations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confirmations")),
    )
    op.create_index(op.f("ix_confirmations_user_id"), "confirmations", ["user_id"], unique=False)
    op.create_index(
        "ix_confirmations_user_status", "confirmations", ["user_id", "status"], unique=False
    )
    op.create_table(
        "foods",
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=True),
        sa.Column("region", sa.String(length=40), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_foods_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_foods")),
    )
    op.create_index(op.f("ix_foods_name"), "foods", ["name"], unique=False)
    op.create_index("ix_foods_name_brand", "foods", ["name", "brand"], unique=False)
    op.create_index(op.f("ix_foods_owner_user_id"), "foods", ["owner_user_id"], unique=False)
    op.create_index(op.f("ix_foods_region"), "foods", ["region"], unique=False)
    op.create_index(op.f("ix_foods_state"), "foods", ["state"], unique=False)
    op.create_table(
        "nutrition_entries",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("meal_type", sa.String(length=20), nullable=False),
        sa.Column("eaten_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("totals", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column(
            "is_flexible_meal", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "meal_type IN ('breakfast', 'lunch', 'dinner', 'snack', 'other')",
            name=op.f("ck_nutrition_entries_meal_type"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_nutrition_entries_version_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_nutrition_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nutrition_entries")),
    )
    op.create_index(
        "ix_nutrition_entries_user_eaten",
        "nutrition_entries",
        ["user_id", "eaten_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nutrition_entries_user_id"), "nutrition_entries", ["user_id"], unique=False
    )
    op.create_table(
        "nutrition_target_drafts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("kcal_min", sa.Numeric(precision=9, scale=2), nullable=False),
        sa.Column("kcal_max", sa.Numeric(precision=9, scale=2), nullable=False),
        sa.Column("protein_min_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("protein_max_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("carbs_min_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("carbs_max_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("fat_min_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("fat_max_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('editing', 'submitted')", name=op.f("ck_nutrition_target_drafts_status")
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_nutrition_target_drafts_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_nutrition_target_drafts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nutrition_target_drafts")),
    )
    op.create_index(
        op.f("ix_nutrition_target_drafts_user_id"),
        "nutrition_target_drafts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "training_plan_drafts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("weekly_frequency", sa.Integer(), nullable=False),
        sa.Column("days", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="editing", nullable=False),
        sa.Column(
            "validation_errors",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "validation_warnings",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('editing', 'submitted')", name=op.f("ck_training_plan_drafts_status")
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name=op.f("ck_training_plan_drafts_name_not_blank")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_training_plan_drafts_version_positive")),
        sa.CheckConstraint(
            "weekly_frequency BETWEEN 1 AND 7",
            name=op.f("ck_training_plan_drafts_weekly_frequency_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_training_plan_drafts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_plan_drafts")),
    )
    op.create_index(
        op.f("ix_training_plan_drafts_user_id"), "training_plan_drafts", ["user_id"], unique=False
    )
    op.create_index(
        "ix_training_plan_drafts_user_status",
        "training_plan_drafts",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "body_measurement_revisions",
        sa.Column("measurement_id", sa.Uuid(), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("new_values", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["measurement_id"],
            ["body_measurements.id"],
            name=op.f("fk_body_measurement_revisions_measurement_id_body_measurements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_body_measurement_revisions")),
    )
    op.create_index(
        op.f("ix_body_measurement_revisions_measurement_id"),
        "body_measurement_revisions",
        ["measurement_id"],
        unique=False,
    )
    op.create_table(
        "food_versions",
        sa.Column("food_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("basis_amount_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("kcal", sa.Numeric(precision=9, scale=2), nullable=False),
        sa.Column("protein_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("carbs_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("fat_g", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "basis_amount_g > 0", name=op.f("ck_food_versions_basis_amount_positive")
        ),
        sa.CheckConstraint(
            "kcal >= 0 AND protein_g >= 0 AND carbs_g >= 0 AND fat_g >= 0",
            name=op.f("ck_food_versions_nutrients_non_negative"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_food_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["foods.id"],
            name=op.f("fk_food_versions_food_id_foods"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_food_versions")),
        sa.UniqueConstraint("food_id", "version", name="uq_food_versions_food_version"),
    )
    op.create_index(op.f("ix_food_versions_food_id"), "food_versions", ["food_id"], unique=False)
    op.create_table(
        "nutrition_entry_revisions",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("new_values", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["nutrition_entries.id"],
            name=op.f("fk_nutrition_entry_revisions_entry_id_nutrition_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nutrition_entry_revisions")),
    )
    op.create_index(
        op.f("ix_nutrition_entry_revisions_entry_id"),
        "nutrition_entry_revisions",
        ["entry_id"],
        unique=False,
    )
    op.create_table(
        "nutrition_target_versions",
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_draft_id", sa.Uuid(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'superseded')", name=op.f("ck_nutrition_target_versions_status")
        ),
        sa.ForeignKeyConstraint(
            ["source_draft_id"],
            ["nutrition_target_drafts.id"],
            name=op.f("fk_nutrition_target_versions_source_draft_id_nutrition_target_drafts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_nutrition_target_versions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nutrition_target_versions")),
        sa.UniqueConstraint(
            "target_id", "version", name="uq_nutrition_target_versions_target_version"
        ),
    )
    op.create_index(
        op.f("ix_nutrition_target_versions_target_id"),
        "nutrition_target_versions",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nutrition_target_versions_user_id"),
        "nutrition_target_versions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_nutrition_target_versions_one_active_user",
        "nutrition_target_versions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "training_plan_versions",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_draft_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("weekly_frequency", sa.Integer(), nullable=False),
        sa.Column("days", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'superseded')", name=op.f("ck_training_plan_versions_status")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_training_plan_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["source_draft_id"],
            ["training_plan_drafts.id"],
            name=op.f("fk_training_plan_versions_source_draft_id_training_plan_drafts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_training_plan_versions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_plan_versions")),
        sa.UniqueConstraint("plan_id", "version", name="uq_training_plan_versions_plan_version"),
    )
    op.create_index(
        op.f("ix_training_plan_versions_plan_id"),
        "training_plan_versions",
        ["plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_plan_versions_user_id"),
        "training_plan_versions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_training_plan_versions_one_active_user",
        "training_plan_versions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "calendar_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="planned", nullable=False),
        sa.Column("plan_version_id", sa.Uuid(), nullable=True),
        sa.Column("plan_day_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("actual_workout_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'completed', 'missed', 'skipped')",
            name=op.f("ck_calendar_events_status"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_version_id"],
            ["training_plan_versions.id"],
            name=op.f("fk_calendar_events_plan_version_id_training_plan_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_calendar_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_events")),
    )
    op.create_index(
        "ix_calendar_events_user_date",
        "calendar_events",
        ["user_id", "scheduled_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_events_user_id"), "calendar_events", ["user_id"], unique=False
    )
    op.create_table(
        "calendar_reschedule_drafts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("missed_event_id", sa.Uuid(), nullable=False),
        sa.Column("strategy", sa.String(length=10), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("before_events", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("after_events", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("duration_change_minutes", sa.Integer(), nullable=False),
        sa.Column("volume_change_percent", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="editing", nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('editing', 'submitted')", name=op.f("ck_calendar_reschedule_drafts_status")
        ),
        sa.CheckConstraint(
            "strategy IN ('shift', 'merge', 'skip')",
            name=op.f("ck_calendar_reschedule_drafts_strategy"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_calendar_reschedule_drafts_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["missed_event_id"],
            ["calendar_events.id"],
            name=op.f("fk_calendar_reschedule_drafts_missed_event_id_calendar_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_calendar_reschedule_drafts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_reschedule_drafts")),
    )
    op.create_index(
        op.f("ix_calendar_reschedule_drafts_user_id"),
        "calendar_reschedule_drafts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "workouts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_event_id", sa.Uuid(), nullable=True),
        sa.Column("plan_day_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "pre_check",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("overall_difficulty", sa.Integer(), nullable=True),
        sa.Column("fatigue", sa.Integer(), nullable=True),
        sa.Column(
            "pain",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("interruption_reason", sa.String(length=1000), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed', 'interrupted')", name=op.f("ck_workouts_status")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_workouts_version_positive")),
        sa.ForeignKeyConstraint(
            ["calendar_event_id"],
            ["calendar_events.id"],
            name=op.f("fk_workouts_calendar_event_id_calendar_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_workouts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workouts")),
    )
    op.create_index(op.f("ix_workouts_user_id"), "workouts", ["user_id"], unique=False)
    op.create_index(
        "ix_workouts_user_started_at", "workouts", ["user_id", "started_at"], unique=False
    )
    op.create_index(
        "uq_workouts_one_active_user",
        "workouts",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.create_table(
        "progression_drafts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("suggestions", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('editing', 'submitted')", name=op.f("ck_progression_drafts_status")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_progression_drafts_version_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_progression_drafts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name=op.f("fk_progression_drafts_workout_id_workouts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progression_drafts")),
    )
    op.create_index(
        op.f("ix_progression_drafts_user_id"), "progression_drafts", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_progression_drafts_workout_id"), "progression_drafts", ["workout_id"], unique=False
    )
    op.create_table(
        "workout_exercises",
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=True),
        sa.Column("original_exercise_id", sa.Uuid(), nullable=True),
        sa.Column("name_snapshot", sa.String(length=120), nullable=False),
        sa.Column("target_snapshot", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column(
            "replacement_history",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_workout_exercises_exercise_id_exercises"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name=op.f("fk_workout_exercises_workout_id_workouts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_exercises")),
        sa.UniqueConstraint("workout_id", "order_no", name="uq_workout_exercises_workout_order"),
    )
    op.create_index(
        op.f("ix_workout_exercises_exercise_id"), "workout_exercises", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_workout_exercises_workout_id"), "workout_exercises", ["workout_id"], unique=False
    )
    op.create_table(
        "workout_sets",
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("workout_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("client_generated_id", sa.Uuid(), nullable=False),
        sa.Column("set_index", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("rir", sa.Integer(), nullable=True),
        sa.Column("rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("reps >= 0", name=op.f("ck_workout_sets_reps_non_negative")),
        sa.CheckConstraint(
            "rir IS NULL OR rir BETWEEN 0 AND 10", name=op.f("ck_workout_sets_rir_range")
        ),
        sa.CheckConstraint(
            "rpe IS NULL OR rpe BETWEEN 1 AND 10", name=op.f("ck_workout_sets_rpe_range")
        ),
        sa.CheckConstraint("set_index >= 1", name=op.f("ck_workout_sets_set_index_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_workout_sets_version_positive")),
        sa.CheckConstraint("weight_kg >= 0", name=op.f("ck_workout_sets_weight_non_negative")),
        sa.ForeignKeyConstraint(
            ["workout_exercise_id"],
            ["workout_exercises.id"],
            name=op.f("fk_workout_sets_workout_exercise_id_workout_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name=op.f("fk_workout_sets_workout_id_workouts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_sets")),
        sa.UniqueConstraint(
            "workout_exercise_id", "set_index", name="uq_workout_sets_exercise_index"
        ),
        sa.UniqueConstraint("workout_id", "client_generated_id", name="uq_workout_sets_client_id"),
    )
    op.create_index(
        op.f("ix_workout_sets_workout_exercise_id"),
        "workout_sets",
        ["workout_exercise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workout_sets_workout_id"), "workout_sets", ["workout_id"], unique=False
    )
    op.create_table(
        "personal_records",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=True),
        sa.Column("exercise_name_snapshot", sa.String(length=120), nullable=False),
        sa.Column("record_type", sa.String(length=30), nullable=False),
        sa.Column("value", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("set_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_personal_records_exercise_id_exercises"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["workout_sets.id"],
            name=op.f("fk_personal_records_set_id_workout_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_personal_records_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name=op.f("fk_personal_records_workout_id_workouts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personal_records")),
    )
    op.create_index(
        op.f("ix_personal_records_exercise_id"), "personal_records", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_personal_records_user_id"), "personal_records", ["user_id"], unique=False
    )
    op.create_index(
        "ix_personal_records_user_occurred",
        "personal_records",
        ["user_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "workout_set_revisions",
        sa.Column("set_id", sa.Uuid(), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("new_values", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["workout_sets.id"],
            name=op.f("fk_workout_set_revisions_set_id_workout_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_set_revisions")),
    )
    op.create_index(
        op.f("ix_workout_set_revisions_set_id"), "workout_set_revisions", ["set_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("confirmations")
    op.drop_table("body_measurement_revisions")
    op.drop_table("body_fat_estimates")
    op.drop_table("body_measurements")
    op.drop_table("nutrition_target_versions")
    op.drop_table("nutrition_target_drafts")
    op.drop_table("nutrition_entry_revisions")
    op.drop_table("nutrition_entries")
    op.drop_table("food_versions")
    op.drop_table("foods")
    op.drop_table("personal_records")
    op.drop_table("progression_drafts")
    op.drop_table("workout_set_revisions")
    op.drop_table("workout_sets")
    op.drop_table("workout_exercises")
    op.drop_table("workouts")
    op.drop_table("calendar_reschedule_drafts")
    op.drop_table("calendar_events")
    op.drop_table("training_plan_versions")
    op.drop_table("training_plan_drafts")
    op.drop_table("training_templates")
