"""create user goals and constraints tables

Revision ID: a84c7376f347
Revises: 1cc1cb7f49d3
Create Date: 2026-08-24 21:12:13.163739

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a84c7376f347"
down_revision: str | Sequence[str] | None = "1cc1cb7f49d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_constraints",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "equipment",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "preferred_exercise_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "disliked_exercise_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "pain_or_injuries",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "allergies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "dietary_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_user_constraints_version_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_constraints_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_constraints")),
    )
    op.create_table(
        "user_goals",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("goal_type", sa.String(length=20), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("target_weight_kg", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="active", nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "goal_type IN "
            "('muscle_gain', 'fat_loss_retain', 'recomposition', 'maintain', 'strength')",
            name=op.f("ck_user_goals_goal_type"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'superseded')", name=op.f("ck_user_goals_goal_status")
        ),
        sa.CheckConstraint(
            "target_weight_kg IS NULL OR (target_weight_kg > 0 AND target_weight_kg <= 500)",
            name=op.f("ck_user_goals_target_weight_kg_range"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_user_goals_version_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_goals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_goals")),
        sa.UniqueConstraint("user_id", "version", name="uq_user_goals_user_id_version"),
    )
    op.create_index(op.f("ix_user_goals_user_id"), "user_goals", ["user_id"], unique=False)
    op.create_index(
        "uq_user_goals_one_active_per_user",
        "user_goals",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_user_goals_one_active_per_user",
        table_name="user_goals",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_user_goals_user_id"), table_name="user_goals")
    op.drop_table("user_goals")
    op.drop_table("user_constraints")
    # ### end Alembic commands ###
