"""create exercise library tables

Revision ID: b41b74dda711
Revises: a84c7376f347
Create Date: 2026-08-25 10:41:08.645854

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b41b74dda711"
down_revision: str | Sequence[str] | None = "a84c7376f347"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("name_zh", sa.String(length=120), nullable=False),
        sa.Column("movement_pattern", sa.String(length=40), nullable=True),
        sa.Column("equipment", sa.String(length=40), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column(
            "instructions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "breathing",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "common_errors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "safety_notes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(equipment)) > 0", name=op.f("ck_exercises_equipment_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(name_zh)) > 0", name=op.f("ck_exercises_name_zh_not_blank")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_exercises_version_positive")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_exercises_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
    )
    op.create_index(op.f("ix_exercises_equipment"), "exercises", ["equipment"], unique=False)
    op.create_index(op.f("ix_exercises_name_zh"), "exercises", ["name_zh"], unique=False)
    op.create_index(
        op.f("ix_exercises_owner_user_id"), "exercises", ["owner_user_id"], unique=False
    )
    op.create_table(
        "exercise_aliases",
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=120), nullable=False),
        sa.Column("normalized_alias", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(alias)) > 0", name=op.f("ck_exercise_aliases_alias_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(normalized_alias)) > 0",
            name=op.f("ck_exercise_aliases_normalized_alias_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_aliases_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_aliases")),
        sa.UniqueConstraint(
            "exercise_id", "normalized_alias", name="uq_exercise_aliases_exercise_normalized"
        ),
    )
    op.create_index(
        op.f("ix_exercise_aliases_exercise_id"), "exercise_aliases", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_aliases_normalized_alias"),
        "exercise_aliases",
        ["normalized_alias"],
        unique=False,
    )
    op.create_table(
        "exercise_media",
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("view_angle", sa.String(length=40), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "media_type IN ('animation', 'image')", name=op.f("ck_exercise_media_media_type")
        ),
        sa.CheckConstraint(
            "length(btrim(storage_key)) > 0", name=op.f("ck_exercise_media_storage_key_not_blank")
        ),
        sa.CheckConstraint("sort_order >= 1", name=op.f("ck_exercise_media_sort_order_positive")),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_media_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_media")),
        sa.UniqueConstraint("storage_key", name="uq_exercise_media_storage_key"),
    )
    op.create_index(
        "ix_exercise_media_exercise_sort_order",
        "exercise_media",
        ["exercise_id", "sort_order"],
        unique=False,
    )
    op.create_table(
        "exercise_muscles",
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("muscle_code", sa.String(length=40), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('primary', 'secondary')", name=op.f("ck_exercise_muscles_role")
        ),
        sa.CheckConstraint(
            "length(btrim(muscle_code)) > 0", name=op.f("ck_exercise_muscles_muscle_code_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_muscles_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("exercise_id", "muscle_code", name=op.f("pk_exercise_muscles")),
    )
    op.create_index(
        "ix_exercise_muscles_muscle_code_role",
        "exercise_muscles",
        ["muscle_code", "role"],
        unique=False,
    )
    op.create_table(
        "exercise_substitutions",
        sa.Column("source_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("target_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(reason)) > 0", name=op.f("ck_exercise_substitutions_reason_not_blank")
        ),
        sa.CheckConstraint(
            "priority >= 1", name=op.f("ck_exercise_substitutions_priority_positive")
        ),
        sa.CheckConstraint(
            "source_exercise_id != target_exercise_id",
            name=op.f("ck_exercise_substitutions_different_exercises"),
        ),
        sa.ForeignKeyConstraint(
            ["source_exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_substitutions_source_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_substitutions_target_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_substitutions")),
        sa.UniqueConstraint(
            "source_exercise_id",
            "target_exercise_id",
            name="uq_exercise_substitutions_source_target",
        ),
    )
    op.create_index(
        "ix_exercise_substitutions_source_priority",
        "exercise_substitutions",
        ["source_exercise_id", "priority"],
        unique=False,
    )
    op.create_index(
        "ix_exercise_substitutions_target",
        "exercise_substitutions",
        ["target_exercise_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_exercise_substitutions_target", table_name="exercise_substitutions")
    op.drop_index("ix_exercise_substitutions_source_priority", table_name="exercise_substitutions")
    op.drop_table("exercise_substitutions")
    op.drop_index("ix_exercise_muscles_muscle_code_role", table_name="exercise_muscles")
    op.drop_table("exercise_muscles")
    op.drop_index("ix_exercise_media_exercise_sort_order", table_name="exercise_media")
    op.drop_table("exercise_media")
    op.drop_index(op.f("ix_exercise_aliases_normalized_alias"), table_name="exercise_aliases")
    op.drop_index(op.f("ix_exercise_aliases_exercise_id"), table_name="exercise_aliases")
    op.drop_table("exercise_aliases")
    op.drop_index(op.f("ix_exercises_owner_user_id"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_name_zh"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_equipment"), table_name="exercises")
    op.drop_table("exercises")
    # ### end Alembic commands ###
