"""create image assets table

Revision ID: fc07f60845fc
Revises: 9a31c6d82f44
Create Date: 2026-08-29 11:20:30.366562

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc07f60845fc"
down_revision: str | Sequence[str] | None = "9a31c6d82f44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_assets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("content_length", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending_upload", nullable=False),
        sa.Column("upload_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("etag", sa.String(length=128), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=1000), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_type IN ('image/jpeg', 'image/png', 'image/webp')",
            name=op.f("ck_image_assets_content_type"),
        ),
        sa.CheckConstraint(
            "purpose IN ('chat_attachment', 'nutrition_entry', 'body_progress')",
            name=op.f("ck_image_assets_purpose"),
        ),
        sa.CheckConstraint(
            "status IN ('pending_upload', 'uploaded', 'ready', 'failed', 'deleted')",
            name=op.f("ck_image_assets_status"),
        ),
        sa.CheckConstraint(
            "content_length > 0", name=op.f("ck_image_assets_content_length_positive")
        ),
        sa.CheckConstraint(
            "length(trim(object_key)) > 0", name=op.f("ck_image_assets_object_key_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_image_assets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_assets")),
        sa.UniqueConstraint("object_key", name="uq_image_assets_object_key"),
    )
    op.create_index(
        "ix_image_assets_status_upload_expiry",
        "image_assets",
        ["status", "upload_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_image_assets_user_created", "image_assets", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_image_assets_user_created", table_name="image_assets")
    op.drop_index("ix_image_assets_status_upload_expiry", table_name="image_assets")
    op.drop_table("image_assets")
    # ### end Alembic commands ###
